org: jsoareez
service: async-process-s3-triggers

provider:
  name: aws
  runtime: nodejs20.x
  region: sa-east-1
  architecture: arm64
  memorySize: 128
  timeout: 25
  environment:
    LIVES_TABLE: !Ref LivesTable
    LIVES_IMAGES_BUCKET: !Ref LivesImagesBucket
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:UpdateItem
          Resource: !GetAtt LivesTable.Arn
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource: !Join ['/', [!GetAtt LivesImagesBucket.Arn, '*']]

package:
  individually: true

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - '@aws-sdk/*'
      - sharp
    external:
      - sharp

layers:
  Sharp:
    name: sharp-layer
    description: sharp package and its binaries.
    path: layers/sharp
    retain: false
    compatibleArchitectures:
      - arm64
    compatibleRuntimes:
      - nodejs20.x

functions:
  createLive:
    handler: src/functions/http/createLive.handler
    events:
      - httpApi:
          path: /lives
          method: POST
  processImage:
    handler: src/functions/triggers/processImage.handler
    timeout: 20
    layers:
      - !Ref SharpLambdaLayer
    events:
      - s3:
          bucket: !Ref LivesImagesBucket
          event: s3:ObjectCreated:*
          existing: true
          forceDeploy: true
          rules:
            - prefix: uploads/

resources:
  Resources:
    # DynamoDB Table
    LivesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: LivesTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    # S3 Bucket
    LivesImagesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: async-process-s3-triggers-images

    # SQS Queue
    ImageProcessingQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ImageProcessingQueue
        VisibilityTimeout: 20
        ReceiveMessageWaitTimeSeconds: 20
        RedrivePolicy:
          maxReceiveCount: 2
          deadLetterTargetArn: !GetAtt ImageProcessingDLQ.Arn
    ImageProcessingDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ImageProcessingDLQ
        MessageRetentionPeriod: 1209600 # 14 days
