org: jsoareez
service: async-process-s3-triggers

provider:
  name: aws
  runtime: nodejs20.x
  region: sa-east-1
  architecture: arm64
  memorySize: 128
  timeout: 25
  environment:
    LIVES_TABLE: !Ref LivesTable
    LIVES_IMAGES_BUCKET: !Ref LivesImagesBucket
  iam:
    role:
      statements:
        - Effect: Allow
          Action: dynamodb:PutItem
          Resource: !GetAtt LivesTable.Arn
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
          Resource: !Join ['/', [!GetAtt LivesImagesBucket.Arn, '*']]

package:
  individually: true

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - '@aws-sdk/*'

functions:
  createLive:
    handler: src/functions/http/createLive.handler
    events:
      - httpApi:
          path: /lives
          method: POST

resources:
  Resources:
    LivesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: LivesTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    LivesImagesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: async-process-s3-triggers-images
